accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.home, name = "home"),
    url(r'login/', views.login, name = "login"),
    url(r'logindata/', views.logindata, name = "logindata"),
    url(r'register/', views.login, name = "register"),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

accounts/forms.py
from django import forms

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login as auth_login


def home(request):
    # if not request.user.is_authenticated:
    # # Return a login form to login
    # else:
    # return redirect('success:page')
    return render(request, 'accounts/home.html')

def login(request):
    return render(request, 'accounts/login.html')

def logindata(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                if request.user.is_authenticated:
                    return redirect('accounts:home')


    return render(request, 'accounts/login.html', {'error':'Login Failure'})

accounts/templates/accounts/home.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<h1>Home</h1>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %} {% block head %}
<title>Login</title>
{% endblock %} {% block body %}
<div>
    <div class="container login_bg">

        <form method="post" action="{% url 'accounts:logindata' %}">
            {% csrf_token %}
            <div class="container">

                <h3>Login</h3>
                <div class="form-group">
                    <label for="uname">Username :</label>
                    <input type="text" class="form-control" name="username" id="uname" required>
                </div>
                <div class="form-group">
                    <label for="pass">Password :</label>
                    <input type="password" class="form-control" name="password" id="pass" required>
                </div>
                {% if error %}
                <div class="form-group">
                    <p class = "pdanger">{{error}}</p>
                </div>
                {% endif %}
                <button type="submit" class="save btn btn-primary">Login</button>
            </div>

        </form>

    </div>
</div>



{% endblock %}

accounts/templates/accounts/name.html
{% extends 'base.html' %}
{% block head %}
<title>Name</title>
{% endblock %}
{% block body %}
<form action="accounts/your_name/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css">
        {% load static %}
        <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css">


        {% block head %}
<title>Base Html</title>
        {% endblock %}
    </head>
    <body>
        {% block body %}
        <h1>Base</h1>
        {% endblock %}
    </body>
</html>